docker:
  db: {}
domains: []
git:
  publication_strategy: main_push
global:
  name: pseudocode
  type: app
  version: 9.1.1
wex:
  migration: 1
  version: 6.0.112
test:
  coverage:
    last_report:
      covered: 551
      excluded: 22
      missing: 114
      percent: 82.85714285714286
      total: 665
